analyzer:
  plugins:
    - custom_lint

  exclude:
    - "**.freezed.dart"
    - "**.g.dart"
    - "**.gr.dart"

custom_lint:
  rules:
    # Core Rules
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - avoid_print
    - use_key_in_widget_constructors

    # Performance & Widget Rules
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - sized_box_for_whitespace
    - use_build_context_synchronously

    # Code Quality Rules
    - always_use_package_imports
    - avoid_relative_lib_imports
    - prefer_final_fields
    - prefer_final_locals
    - unnecessary_const
    - unnecessary_new

    # Existing Dart lints
    - always_put_doc_comments_before_annotations
    - always_specify_parameter_names
    - avoid_dynamic
    - avoid_inverted_boolean_expressions
    - avoid_mutable_global_variables
    - avoid_nested_if
    - avoid_positional_fields_in_records
    - avoid_redundant_pattern_field_names
    - avoid_unused_parameters
    - no_duplicate_imports
    - no_self_comparisons
    - prefer_async_await
    - prefer_const_constructor_declarations
    - prefer_iterable_any
    - prefer_iterable_every
    - prefer_iterable_first
    - prefer_iterable_last
    - prefer_library_prefixes
    - prefer_underscore_for_unused_callback_parameters
    - unnecessary_nullable_return_type

    # Existing Flutter lints
    - avoid_returning_widgets
    - avoid_single_child_in_flex
    - avoid_public_members_in_states
    - dispose_controllers
    - prefer_async_callback
    - prefer_border_from_border_side
    - prefer_border_radius_all
    - prefer_dedicated_media_query_functions
    - prefer_text_rich
    - prefer_void_callback
    - proper_edge_insets_constructors
    - proper_expanded_and_flexible
    - proper_from_environment
    - proper_super_dispose
    - proper_super_init_state
    - use_spacer
