// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:game_release_calendar/src/domain/enums/filter/release_precision_filter.dart';
import 'package:game_release_calendar/src/domain/enums/game_category.dart';
import 'package:game_release_calendar/src/domain/enums/game_status.dart';
import 'package:game_release_calendar/src/domain/enums/game_update_type.dart';
import 'package:game_release_calendar/src/domain/enums/release_date_category.dart';
import 'package:game_release_calendar/src/domain/enums/release_region.dart';
import 'package:game_release_calendar/src/domain/enums/supported_game_platform.dart';
import 'package:game_release_calendar/src/domain/models/artwork.dart';
import 'package:game_release_calendar/src/domain/models/cover.dart';
import 'package:game_release_calendar/src/domain/models/game.dart';
import 'package:game_release_calendar/src/domain/models/game_update_log.dart';
import 'package:game_release_calendar/src/domain/models/notifications/game_reminder.dart';
import 'package:game_release_calendar/src/domain/models/platform.dart';
import 'package:game_release_calendar/src/domain/models/release_date.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ArtworkAdapter());
    registerAdapter(CoverAdapter());
    registerAdapter(GameAdapter());
    registerAdapter(GameCategoryAdapter());
    registerAdapter(GameReminderAdapter());
    registerAdapter(GameStatusAdapter());
    registerAdapter(GameUpdateLogAdapter());
    registerAdapter(GameUpdateTypeAdapter());
    registerAdapter(PlatformAdapter());
    registerAdapter(ReleaseDateAdapter());
    registerAdapter(ReleaseDateCategoryAdapter());
    registerAdapter(ReleasePrecisionFilterAdapter());
    registerAdapter(ReleaseRegionAdapter());
    registerAdapter(SupportedGamePlatformAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ArtworkAdapter());
    registerAdapter(CoverAdapter());
    registerAdapter(GameAdapter());
    registerAdapter(GameCategoryAdapter());
    registerAdapter(GameReminderAdapter());
    registerAdapter(GameStatusAdapter());
    registerAdapter(GameUpdateLogAdapter());
    registerAdapter(GameUpdateTypeAdapter());
    registerAdapter(PlatformAdapter());
    registerAdapter(ReleaseDateAdapter());
    registerAdapter(ReleaseDateCategoryAdapter());
    registerAdapter(ReleasePrecisionFilterAdapter());
    registerAdapter(ReleaseRegionAdapter());
    registerAdapter(SupportedGamePlatformAdapter());
  }
}
