// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF1zwSSXM7MszjRUo_6HG8aXDE8tb7swM',
    appId: '1:208744369789:web:5c89bc4a31b1a06b612b14',
    messagingSenderId: '208744369789',
    projectId: 'game-watch-3bd32',
    authDomain: 'game-watch-3bd32.firebaseapp.com',
    storageBucket: 'game-watch-3bd32.firebasestorage.app',
    measurementId: 'G-WMZSF8P3B4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlWwv-F3zKLYeqpqMc5WE_Ayes3SdoAIA',
    appId: '1:208744369789:android:8f7f58c8808d5c35612b14',
    messagingSenderId: '208744369789',
    projectId: 'game-watch-3bd32',
    storageBucket: 'game-watch-3bd32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuPCW6JNlgJbvPRGGuHV9ZrzNW9hhxAts',
    appId: '1:208744369789:ios:2d2d65e896917ef9612b14',
    messagingSenderId: '208744369789',
    projectId: 'game-watch-3bd32',
    storageBucket: 'game-watch-3bd32.firebasestorage.app',
    iosBundleId: 'com.example.gameReleaseCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuPCW6JNlgJbvPRGGuHV9ZrzNW9hhxAts',
    appId: '1:208744369789:ios:2d2d65e896917ef9612b14',
    messagingSenderId: '208744369789',
    projectId: 'game-watch-3bd32',
    storageBucket: 'game-watch-3bd32.firebasestorage.app',
    iosBundleId: 'com.example.gameReleaseCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF1zwSSXM7MszjRUo_6HG8aXDE8tb7swM',
    appId: '1:208744369789:web:d8b0fa1df3f03bf1612b14',
    messagingSenderId: '208744369789',
    projectId: 'game-watch-3bd32',
    authDomain: 'game-watch-3bd32.firebaseapp.com',
    storageBucket: 'game-watch-3bd32.firebasestorage.app',
    measurementId: 'G-81LQDJC4QS',
  );
}
